# Generated by Django 5.0.2 on 2024-06-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads'),
        ),
    ]
