# Generated by Django 5.0.2 on 2024-07-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
